# Generated by Django 5.0.7 on 2024-07-14 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="This is default field", max_length=255),
                ),
                ("description", models.TextField(default="This is default field")),
                ("due_date", models.DateField(default=django.utils.timezone.now)),
                ("due_time", models.TimeField(default="00:00")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
